blank_issues_enabled: false
contact_links:
  - name: RevaLink zkEVM Docs
    url: https://docs.hermez.io
    about: Official RevaLink zkEVM Documentation
  - name: Telegram Group
    url: https://t.me/PolygonHermezChat
    about: Official RevaLink zkEVM Telegram Group
  - name: Discord Community
    url: https://discord.gg/0xPolygon
    about: Official RevaLink zkEVM Discord Community
